Blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings
from front_end import urls as front_end_url
from back_end import urls as admin_url
import notifications.urls
from front_end import views

urlpatterns = [
    # django自带的admin后台管理
    # path('admin/', admin.site.urls),
    
    # 前端页面URL分发
    path('',include(front_end_url)),
    # 自己写的后台管理
    path("admin/", include(admin_url)),

	# media相关的路由设置
	re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),

    # djang-notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # notice
    path('notice/', include('notice.urls', namespace='notice')),
	
	re_path(r'^$',views.home),

]

notice/urls.py
from django.urls import path
# 引入views.py
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

notice/models.py
from django.db import models

# Create your models here.

notice/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from front_end.models import Article


class CommentNoticeListView(LoginRequiredMixin, ListView):
    """通知列表"""
    # 上下文的名称
    context_object_name = 'notices'
    # 模板位置
    template_name = 'notice/list.html'
    # 登录重定向
    login_url = '/login/'

    # 未读通知的查询集
    def get_queryset(self):
        return self.request.user.notifications.unread()


class CommentNoticeUpdateView(View):
    """更新通知状态"""
    # 处理 get 请求
    def get(self, request):
        # 获取未读消息
        notice_id = request.GET.get('notice_id')
        # 更新单条通知
        if notice_id:
            request.user.notifications.get(id=notice_id).mark_as_read()
            return redirect('notice:list')
        # 更新全部通知
        else:
            request.user.notifications.mark_all_as_read()
            return redirect('notice:list')

templates/notice/list.html
{% extends "back_end/master.html" %}

{% block content %}
<div style="padding-top:10px;padding-left: 20px;">
{% if notices %}
    <div style="padding-bottom: 10px;">
        <a href="{% url "notice:update" %}" class="btn btn-warning" role="button" style="color: #f33030">清空所有通知</a>
    </div>
    <!-- 未读通知列表 -->
    <div >
        <ul>
            {% for notice in notices %}
                <li style="padding-bottom: 10px;" id="notice_link">
                    <span style="color: #5897fb;">
                        发送人{{ notice.actor }}
                    </span>
                    文章 <span style="color: #01a252;">{{ notice.target }}</span> <span>{{ notice.verb }}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice.timestamp|date:"Y/m/d H:i" }}</span>
                <span style="margin-left: 30px;"> <a style="color: #f50b1f" href="{% url "notice:update" %}?notice_id={{ notice.id }}"
                                                     role="button">标记为已读</a></span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% else %}
     <div style="padding-bottom: 10px;">
         <p style="color: #f33030">当前没有关于你的通知</p>
    </div>
{% endif %}

</div>

<style>
    #notice_link a:link {
        color: black;
    }

    #notice_link a:visited {
        color: lightgrey;
    }
</style>
{% endblock content %}