Blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings
from front_end import urls as front_end_url
from back_end import urls as admin_url
import notifications.urls
from front_end import views

urlpatterns = [
    # django自带的admin后台管理
    # path('admin/', admin.site.urls),
    
    # 前端页面URL分发
    path('',include(front_end_url)),
    # 自己写的后台管理
    path("admin/", include(admin_url)),

	# media相关的路由设置
	re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),

    # djang-notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # notice
    path('notice/', include('notice.urls', namespace='notice')),
	
	re_path(r'^$',views.home),

]

back_end/urls.py
from django.urls import path, re_path
from django.views.static import serve
from back_end import views


urlpatterns = [
    path('index/', views.index),
    path('welcome/', views.welcome),
    path('article_list/', views.article_list),
    path('article_class/', views.article_class),
    re_path(r'^article_class_edit/(\w+)/', views.article_class_edit),
    path('all_article/', views.all_article),
    path('user_article/', views.user_article),
    path('user_article_release/', views.user_article_release),
    path('user_article_draft/', views.user_article_draft),
    path('user_article_review/', views.user_article_review),
    path('user_article_recycle/', views.user_article_recycle),
    path('release_draft/',views.release_draft),
    path('draft_recycle/', views.draft_recycle),
    path('draft_review/', views.draft_review),
    path('recycle_draft/', views.recycle_draft),
    path('recycle_delete/', views.recycle_delete),
	re_path('review_view/(\d+)/', views.review_view),
    path('review_yes/', views.review_yes),
    path('review_no/', views.review_no),
    path('article_class_delete/', views.article_class_delete),
    path('article_class_add/', views.article_class_add),
    path('article_add/', views.article_add),
    path('article_add_review/', views.article_add_review),
    re_path('article_updata_details/(\d+)/', views.article_updata_details),
    path('comment_list/', views.comment_list),
    re_path('comment_update/(\d+)/',views.comment_update),
    path('comment_del/', views.comment_del),
    path('comment_all_del/', views.comment_all_del),
    path('admin_index/', views.admin_index),
    path('admin_list/', views.admin_list),
    path('user_is_superuser/',views.user_is_superuser),
    path('user_del/',views.user_del),
    path('user_all_del/',views.user_all_del),
    path('admin_updata_details/', views.admin_updata_details),
    path('admin_ad_poster/', views.admin_ad_poster),
    path('ad_poster_add/', views.ad_poster_add),
    re_path('ad_poster_update/(\d+)/', views.ad_poster_update),
    path('ad_poster_del/', views.ad_poster_del),
    path('ad_poster_all_del/', views.ad_poster_all_del),
    path('ad_poster_is_show/', views.ad_poster_is_show),
    path('links/', views.links),
    path('links_add/',views.links_add),
    re_path('links_update/(\d+)/',views.links_update),
    path('links_is_show/',views.links_is_show),
    path('links_del/',views.links_del),
    path('links_all_del/',views.links_all_del),

    # 博客内容上传图片
    path('api-upload-url/', views.api_upload_url),
    # 预览文章
    re_path('article_view/(\d+)/', views.article_view),

]

front_end/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from mptt.models import MPTTModel, TreeForeignKey
from django.urls import reverse
from datetime import datetime
# Django-taggit
from taggit.managers import TaggableManager


# Create your models here.


class UserInfo(AbstractUser):
    """
    用户信息表
    """
    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to="avatars/", default="avatars/default.png", verbose_name="头像")
    create_time = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.username


class EmailVerifyRecord(models.Model):
    """
    邮箱验证码
    """
    code = models.CharField(max_length=20, verbose_name=u"验证码")
    email = models.EmailField(max_length=50, verbose_name=u"邮箱")
    # 包含注册验证和找回验证
    send_type = models.CharField(verbose_name=u"验证码类型", max_length=10,
                                 choices=(("register", u"注册"), ("forget", u"找回密码")))
    send_time = models.DateTimeField(verbose_name=u"发送时间", default=datetime.now)

    class Meta:
        verbose_name = u"邮箱验证码"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return '{0}({1})'.format(self.code, self.email)


class Classification(models.Model):
    """
    文章分类
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 分类标题

    def __str__(self):
        return self.title


class Label(models.Model):
    """
    标签
    """
    nid = models.AutoField(primary_key=True)
    tags = TaggableManager()  # 标签
    article_id = models.OneToOneField(to="Article", to_field="nid", on_delete=models.CASCADE, null=True)


class Article(models.Model):
    """
    文章
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')  # 文章标题
    desc = models.CharField(max_length=255, verbose_name='文章摘要')  # 文章摘要
    create_time = models.DateTimeField(verbose_name='创建时间')  # 创建时间
    cover_photo = models.FileField(upload_to="cover_photo/", default="cover_photo/default.png", verbose_name="封面图片")
    is_draft = models.IntegerField(verbose_name='是否为草稿', default=1)
    is_review = models.IntegerField(verbose_name='是否审核', default=0)
    is_release = models.IntegerField(verbose_name='是否发布', default=0)
    is_recycle = models.IntegerField(verbose_name="是否在回收站", default=0)
    browse_count = models.IntegerField(verbose_name='浏览数', default=0)
    comment_count = models.IntegerField(verbose_name='评论数', default=0)
    like_count = models.IntegerField(verbose_name='喜欢数', default=0)
    user = models.ForeignKey(to="UserInfo", to_field="nid", on_delete=models.CASCADE)
    classification = models.ForeignKey(to="Classification", to_field="nid", on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0, editable=False, verbose_name="阅读数")
    # 采用 Django-taggit 库
    tags = TaggableManager(blank=False, through=None)

    def __str__(self):
        return self.title

    # 浏览数，每一次浏览都自动加一
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_tags(self):
        tags = []
        self.tags.all()
        tags.append(str(tags))
        return ','.join(tags)

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('front_end:article_detail', args=[self.nid])


class ArticleDetail(models.Model):
    """
    文章详情表

    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article = models.OneToOneField(to="Article", to_field="nid", on_delete=models.CASCADE)


class ArticleLike(models.Model):
    """
    喜欢表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo", to_field="nid", null=True, on_delete=models.CASCADE)
    article = models.ForeignKey(to="Article", to_field="nid", null=True, on_delete=models.CASCADE)
    like_ip = models.CharField(max_length=20, verbose_name="评论电脑的IP", null=True)

    class Meta:
        unique_together = (("article", "user"),)


class Comment(MPTTModel):
    """
    评论表
    """
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE, related_name='comments')
    # mptt树形结构
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    # 记录二级评论回复给谁, str
    reply_to = models.ForeignKey(UserInfo, null=True, blank=True, on_delete=models.CASCADE, related_name='replyers')
    body = models.CharField(max_length=800)  # 评论内容
    created = models.DateTimeField(verbose_name='创建时间')

    class MPTTMeta:
        order_insertion_by = ["-created"]

    def __str__(self):
        return self.body



class ad_poster(models.Model):
    """
    广告
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=20, verbose_name="广告标题")
    ad_url = models.CharField(max_length=50, verbose_name="广告链接")
    ad_photo = models.FileField(upload_to="advertisement/", verbose_name="广告图片")
    is_show = models.IntegerField(default=1, verbose_name="是否在前台展示")
    is_rotation = models.IntegerField(default=1, verbose_name="是否在前台轮播展示")
    create_time = models.DateTimeField(verbose_name='创建时间')  # 创建时间


class Links(models.Model):
    """
    :友情链接
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=30, verbose_name="链接名")
    url = models.CharField(max_length=50, verbose_name="链接URL")
    create_time = models.DateTimeField(verbose_name='创建时间')  # 创建时间
    is_show = models.IntegerField(default=1, verbose_name="是否在前台展示")

templates/back_end/ad_poster.html
{% extends "back_end/master.html" %}
{% block content %}
    <div class="layui-fluid">
        <div class="layui-row layui-col-space15">
            <div class="layui-col-md12">
                <div class="layui-card" style="padding-top: 20px">
                    <div class="layui-card-header">
                        <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量删除
                        </button>
                        <button class="layui-btn" onclick="xadmin.open('添加广告信息','/admin/ad_poster_add/',600,400)"><i
                                class="layui-icon"></i>添加广告信息
                        </button>
                    </div>
                    <div class="layui-card-body ">
                        <table class="layui-table">
                            <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" onclick="change()" id="all" name="all" value="全选"
                                           style="display: inline"/>&nbsp;全选
                                </th>
                                <th>ID</th>
                                <th>广告标题</th>
                                <th>广告图片<p style="font-size: 10px;color: #ff070c">(点击图片可以放大)</p></th>
                                <th>广告链接</th>
                                <th>创建时间</th>
                                <th>是否启用</th>
                                <th>操作</th>
                            </thead>
                            <tbody id="layer-photos-demo">
                            {% for ad in ad_poster %}
                                <tr>
                                    <td>
                                        <input type="checkbox" id="che" name="che" style="display: inline">
                                    </td>
                                    <td name="id_pk">{{ ad.pk }}</td>
                                    <td>{{ ad.title }}</td>
                                    <td><img src="/media/{{ ad.ad_photo }}" style="width:100px;height: 40px;"></td>
                                    <td>{{ ad.ad_url }}</td>
                                    <td>{{ ad.create_time|date:"Y-m-d H:i" }}</td>
                                    {% if ad.is_show == 1 %}
                                        <td class="td-status">
                                            <span class="layui-btn layui-btn-normal layui-btn-mini">已启用</span></td>
                                        <td class="td-manage">
                                            <a onclick="member_stop({{ ad.pk }})" href="#" title="停用"
                                               style="padding-left: 10px">
                                                <i class="layui-icon">&#xe601;</i>
                                            </a>
                                            <a title="编辑" onclick="xadmin.open('编辑','admin/ad_poster_update/{{ ad.pk }}/')"
                                               href="javascript:;"
                                               style="padding-left: 10px">
                                                <i class="layui-icon">&#xe642;</i>
                                            </a>
                                            <a title="删除" onclick="member_del({{ ad.pk }})" href="#"
                                               style="padding-left: 10px">
                                                <i class="layui-icon">&#xe640;</i>
                                            </a>
                                        </td>
                                    {% else %}
                                        <td class="td-status">
                                            <span class="layui-btn layui-btn-normal layui-btn-mini layui-btn-disabled">已停用</span>
                                        </td>
                                        <td>
                                            <a onclick="member_up({{ ad.pk }})" href="javascript:;" title="启用"
                                               style="padding-left: 10px">
                                                <i class="layui-icon">&#xe62f;</i>
                                            </a>
                                            <a title="编辑" onclick="xadmin.open('编辑','admin/ad_poster_update/{{ ad.pk }}/')"
                                               href="javascript:;"
                                               style="padding-left: 10px">
                                                <i class="layui-icon">&#xe642;</i>
                                            </a>
                                            <a title="删除" onclick="member_del({{ ad.pk }})" href="javascript:;"
                                               style="padding-left: 10px">
                                                <i class="layui-icon">&#xe640;</i>
                                            </a>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block jquery %}
    <script src="/static/back_end/lib/layui/layui.all.js"></script>
    <script type="text/javascript">
        /*图片放大*/
        layer.photos({
            photos: '#layer-photos-demo',
            anim: 0,
        });
    </script>
    <script>
        /*用户-停用*/
        function member_stop(id) {
            layer.confirm('确认要停用吗？', function () {
                //发异步把用户状态进行更改
                $.ajax({
                    url: "/admin/ad_poster_is_show/",
                    type: "post",
                    data: {
                        pid: id,
                        is_show: 1,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    success: function (data) {
                        if (data.status === 1) {
                            layer.msg('已停用!', {icon: 5, time: 1000});
                            window.location.reload();
                        }
                    },
                })
            })
        }
        /*用户-启用*/
        function member_up(id) {
            layer.confirm('确认要启用吗？', function () {
                //发异步把用户状态进行更改
                $.ajax({
                    url: "/admin/ad_poster_is_show/",
                    type: "post",
                    data: {
                        pid: id,
                        is_show: 0,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    success: function (data) {
                        if (data.status === 1) {
                            layer.msg('已启用!', {icon: 5, time: 1000});
                            window.location.reload();
                        }
                    },
                })
            })
        }
        /*用户-删除*/
        function member_del(id) {
            layer.confirm('确认要删除吗？', function (index) {
                //发异步删除数据
                $.ajax({
                    url: "/admin/ad_poster_del/",
                    type: "post",
                    data: {
                        pid: id,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    success: function (data) {
                        if (data.status === 1) {
                            alert(data.msg);
                            layer.msg('已删除!', {icon: 1, time: 1000});
                            window.location.reload();
                        } else {
                            alert('删除失败！');
                        }
                    },
                });
            });
        }

        var allpro = document.getElementsByName("che");

        //全选方法
        function change() {
            //获取全选按钮
            var all = document.getElementById("all");
            //全选按钮被选中时，遍历所有按钮
            if (all.checked) {
                for (var i = 0; i < allpro.length; i++) {
                    if (allpro[i].type === "checkbox") {
                        allpro[i].checked = true;

                    }
                }
                //全选按钮未被选中时
            } else {
                for (var i = 0; i < allpro.length; i++) {
                    if (allpro[i].type === "checkbox") {
                        allpro[i].checked = false;
                    }
                }
            }
        }

        //批量删除
        function delAll() {
            var ck = $("input:checked[name='che']");
            if (ck.length === 0) {
                alert("请选择,然后进行删除");
                return;
            }
            var f = confirm("确认删除!!");
            if (!f) {
                return;
            }
            ids = ck.parent('td').parent('tr').find("[name='id_pk']").map(function () {
                return this.innerHTML
            }).get().join();
            $.ajax({
                url: "/admin/ad_poster_all_del/",
                type: "post",
                data: {
                    pid: ids,
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                success: function (data) {
                    if (data.status === 1) {
                        alert(data.msg);
                        window.location.reload();
                    } else {
                        alert('删除失败！');
                    }
                },
            });
        }
    </script>

    <script>
        var _hmt = _hmt || [];
        (function () {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
{% endblock %}

templates/back_end/ad_poster_add.html
{% extends "back_end/master.html" %}
{% block content %}

    <div class="admin-div-back" style="padding-left: 100px;">
        {% csrf_token %}
        <div style="padding-top: 20px;float: none">
            <p style="margin-top: 15px;font-size: 25px"> 广告标题：<input type="text" id='title' style="width: 400px;height: 30px;"></p>
            <p style="margin-top: 15px;font-size: 25px"> 广告链接：<input type="text" id='url' style="width: 400px;height: 30px;"></p>
        </div>
        <div style="padding-top: 30px;margin-bottom: 10px;width: 500px;">
            <label style="font-size: 20px">选择广告图片</label><br>
            <label style="color: red;margin-top: 3px">（点击图片上传广告图片）</label>
            <div class="admin-div-back" style="margin-top: 5px">
                <label for="id_avatar"><img style="width: 100%; height: 200px;" id="avatar-img"
                                            src="/media/advertisement/601554968669_.pic_hd.jpg"
                                            alt=""></label>
            </div>
            <input accept="image/*" type="file" name="avatar" id="id_avatar"
                   style="display: none">
        </div>
        <div style="padding-top: 20px">
            <button class="layui-btn layui-btn-lg layui-btn-warm" onclick="ad_poster_updata()">提交</button>
            &nbsp;&nbsp;<label id="error_messages" style="font-size: 20px;color: red"></label>
        </div>
    </div>
{% endblock %}
{% block jquery %}
    <script src="/static/jquery-3.3.1.js"></script>
    <script>
        // 找到封面的input标签绑定change事件
        $("#id_avatar").change(function () {
            // 1. 创建一个读取文件的对象
            var fileReader = new FileReader();
            // 取到当前选中的封面文件
            // console.log(this.files[0]);
            // 读取你选中的封面文件
            fileReader.readAsDataURL(this.files[0]);  // 读取文件是需要时间的
            fileReader.onload = function () {
                // 2. 等上一步读完文件之后才 把图片加载到img标签中
                $("#avatar-img").attr("src", fileReader.result);
            };
        })
    </script>
    <script>
        function ad_poster_updata() {
            var formData = new FormData();
            formData.append("title", $("#title").val());
            formData.append("url", $("#url").val());
            formData.append("avatar", $("#id_avatar")[0].files[0]);
            formData.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

            //发异步提交数据
            $.ajax({
                url: "/admin/ad_poster_add/",
                type: "post",
                processData: false,
                contentType: false,
                data: formData,
                success: function (data) {
                    if (data.status === 1) {
                        alert(data.msg);
                        parent.location.reload(); //刷新到父亲对象（框架）
                    } else {
                        $("#error_messages").text(data.msg);
                    }
                },
            });
        }
    </script>
{% endblock %}

templates/back_end/admin_index.html
{% extends "back_end/master.html" %}
{% block content %}
    <div class="layui-fluid">
        <div class="layui-row layui-col-space15">
            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-body ">
                        <div class="layui-input-inline layui-shw-xs-block">
                            <div id="show_all_article">
                                <div class="layui-card-body ">
                                    <table class="layui-table" lay-even="" lay-skin="nob"
                                           style="width:100%;font-size: 20px;">
                                        <tbody>
                                        <tr>
                                            <td style="width: 600px;margin-left: 40%;">头像:<img
                                                    style="width: 80px;height: 80px;margin-left: 20px"
                                                    src="/media/{{ my_details.avatar }}"></td>
                                        </tr>
                                        <tr>
                                            <td style="width: 600px;margin-left: 40%;">用户名：<span
                                                    style="margin-left: 20px;margin-top: 10px">{{ my_details.username }}</span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="width: 600px;margin-left: 40%;">手机号：<span
                                                    style="margin-left: 20px;margin-top: 10px">{{ my_details.phone }}</span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="width: 600px;margin-left: 40%;">邮箱：<span
                                                    style="margin-left: 20px;margin-top: 10px">{{ my_details.email }}</span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="width: 600px;">
                                                <button class="layui-btn layui-btn "
                                                        onclick="xadmin.open('编辑','/admin/admin_updata_details/' )">
                                                    <i class="layui-icon">&#xe642;</i>编辑
                                                </button>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/back_end/admin_updata_details.html
{% extends "back_end/master.html" %}
{% block content %}

    <div class="admin-div-back" style="padding-left: 100px;">
        {% csrf_token %}
        <div style="padding-top: 30px;margin-bottom: 10px;width: 80px;">
            <label style="font-size: 20px">选择头像</label><br>
            <label style="color: red;margin-top: 3px">（点击图片上传封面图片）</label>
            <div class="admin-div-back" style="margin-top: 5px">
                <label for="id_avatar"><img style="width: 100%; height: 80px;" id="avatar-img"
                                            src="/media/{{ my_details.avatar }}"
                                            alt=""></label>
            </div>
            <input accept="image/*" type="file" name="avatar" id="id_avatar"
                   style="display: none">
        </div>
        <div style="margin-top: 20px;float: none">
            <p style="margin-top: 15px;font-size: 15px"> 修改用户名：<input type="text" id='username'
                                                                      value="{{ my_details.username }}"></p>
            <p style="margin-top: 15px;font-size: 15px"> 修改密码：<input type="text" id='password' value="请输入密码"></p>
            <P style="margin-top: 15px;font-size: 15px">修改邮箱：<input type="text" id="email"
                                                                    value="{{ my_details.email }}">
            </P>
            <p style="margin-top: 15px;font-size: 15px">修改手机号：<input type="text" id="phone"
                                                                     value="{{ my_details.phone }}">
            </p>
        </div>
        <div style="padding-top: 20px">
            <button class="layui-btn layui-btn-lg layui-btn-warm" onclick="admin_updata()">提交修改</button>
            <div><label id="error_messages" style="font-size: 20px;color: red"></label></div>
        </div>
    </div>
{% endblock %}
{% block jquery %}
    <script src="/static/jquery-3.3.1.js"></script>
    <script>
        // 找到封面的input标签绑定change事件
        $("#id_avatar").change(function () {
            // 1. 创建一个读取文件的对象
            var fileReader = new FileReader();
            // 取到当前选中的封面文件
            // console.log(this.files[0]);
            // 读取你选中的封面文件
            fileReader.readAsDataURL(this.files[0]);  // 读取文件是需要时间的
            fileReader.onload = function () {
                // 2. 等上一步读完文件之后才 把图片加载到img标签中
                $("#avatar-img").attr("src", fileReader.result);
            };
        })
    </script>
    <script>
        function admin_updata() {
            var formData = new FormData();
            formData.append("username", $("#username").val());
            formData.append("password", $("#password").val());
            formData.append("email", $("#email").val());
            formData.append("phone", $("#phone").val());
            formData.append("avatar", $("#id_avatar")[0].files[0]);
            formData.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

            //发异步提交数据
            $.ajax({
                url: "/admin/admin_updata_details/",
                type: "post",
                processData: false,
                contentType: false,
                data: formData,
                success: function (data) {
                    if (data.status === 1) {
                        alert(data.msg);
                        window.history.back(-1);
                    } else {
                        $("#error_messages").text(data.msg);
                    }
                },
            });
        }
    </script>
{% endblock %}


templates/back_end/all_article.html
{% extends "back_end/article_list.html" %}
{% block classify %}
    <div class="layui-card-body ">
        <table class="layui-table layui-form">
            <thead>
            <tr>
                <th>标题</th>
                <th>作者</th>
                <th>分类目录</th>
                <th>日期</th>
                <th>浏览数</th>
                <th>点赞数</th>
                <th>评论数</th>
                <th></th>
            </tr>
            </thead>
            <tbody>

            {% for article in page %}
                <tr>
                    <td>{{ article.title }}</td>
                    <td>{{ article.user.username }}</td>
                    <td>{{ article.classification.title }}</td>
                    {% if article.is_release == 1 %}
                        <td><p>已发布</p>{{ article.create_time|date:"Y-m-d H:i" }}</td>
                    {% else %}
                        <td><p>最后修改</p>{{ article.create_time|date:"Y-m-d H:i" }}</td>
                    {% endif %}
                    <td>{{ article.views }}</td>
                    <td>{{ article.like_count }}</td>
                    <td>{{ article.comment_count }}</td>
                    <td>
                        <button class="layui-btn layui-btn-xs"
                                onclick="xadmin.open('查看','/admin/article_view/{{ article.pk }}/')">
                            <i class="layui-icon">&#xe615;</i>查看
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include "back_end/page.html" %}
    </div>
{% endblock %}
{% block jquery %}
    <script>
        $("#show_all_article").attr("style", "display:none;");//隐藏div
    </script>
    <script src="/static/back_end/lib/layui/layui.js"></script>
{% endblock %}

templates/back_end/article_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查看文章</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/my_style.css' %}">
    <link rel="stylesheet" href="{% static '/prism_patched.min.css' %}">
    {# 语法高亮 #}
</head>
<body>
<div class="div-back" id="test-editormd-view">
    <p style="font-size: 30px; text-align: center;padding: 10px 0 10px 0">{{ details.article.title }}</p>
        <div id="details_content">
    <p>{{ details.content|safe }}</p>
            </div>
</div>
</body>
</html>