Blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings
from front_end import urls as front_end_url
from back_end import urls as admin_url
import notifications.urls
from front_end import views

urlpatterns = [
    # django自带的admin后台管理
    # path('admin/', admin.site.urls),
    
    # 前端页面URL分发
    path('',include(front_end_url)),
    # 自己写的后台管理
    path("admin/", include(admin_url)),

	# media相关的路由设置
	re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),

    # djang-notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # notice
    path('notice/', include('notice.urls', namespace='notice')),
	
	re_path(r'^$',views.home),

]

front_end/urls.py
from django.urls import path, re_path
from django.views.static import serve
from front_end import views
from front_end.views import ActiveUserView
app_name = "front_end"

urlpatterns = [
    path('home/', views.home, name="front_end_home"),
    # 注册于登录
    path("login/", views.login,name="front_end_login"),
    path("register/", views.register, name="front_end_register"),
    path('logout/', views.logout),
    path("forgot_password/", views.forgot_password, name="front_end_forgot_password"),
    # 专门用来校验用户名是否已被注册的接口
    path('check_username_exist/', views.check_username_exist),
    # 用来验证邮箱连接是否被激活
    re_path(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),  # 提取出active后的所有字符赋给active_code
    # 用来找回密码
    re_path(r'^update_password/(?P<forget_code>.*)/$', views.update_password, name="front_end_update_password"),

    # 极验滑动验证码 获取验证码的url
	path('pc-geetest/register', views.get_geetest),
    # 文章类
    re_path(r'^article_category/(\w+)/', views.category),
	re_path(r'^acticle_details/(\d+)/', views.article_details, name="article_detail"),
	re_path(r'^author/(\w+)/', views.author_article),
	re_path(r'^article_data/(.*)/', views.article_data),
    re_path(r'^article_tag/(.*)/', views.article_tag),
	path('article_like/',views.article_like),
	path('search_for/',views.search_for),
    # 发表评论
    re_path('comment/(\d+)/', views.comment,),
]

front_end/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from mptt.models import MPTTModel, TreeForeignKey
from django.urls import reverse
from datetime import datetime
# Django-taggit
from taggit.managers import TaggableManager


# Create your models here.


class UserInfo(AbstractUser):
    """
    用户信息表
    """
    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to="avatars/", default="avatars/default.png", verbose_name="头像")
    create_time = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.username


class EmailVerifyRecord(models.Model):
    """
    邮箱验证码
    """
    code = models.CharField(max_length=20, verbose_name=u"验证码")
    email = models.EmailField(max_length=50, verbose_name=u"邮箱")
    # 包含注册验证和找回验证
    send_type = models.CharField(verbose_name=u"验证码类型", max_length=10,
                                 choices=(("register", u"注册"), ("forget", u"找回密码")))
    send_time = models.DateTimeField(verbose_name=u"发送时间", default=datetime.now)

    class Meta:
        verbose_name = u"邮箱验证码"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return '{0}({1})'.format(self.code, self.email)


class Classification(models.Model):
    """
    文章分类
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 分类标题

    def __str__(self):
        return self.title


class Label(models.Model):
    """
    标签
    """
    nid = models.AutoField(primary_key=True)
    tags = TaggableManager()  # 标签
    article_id = models.OneToOneField(to="Article", to_field="nid", on_delete=models.CASCADE, null=True)


class Article(models.Model):
    """
    文章
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')  # 文章标题
    desc = models.CharField(max_length=255, verbose_name='文章摘要')  # 文章摘要
    create_time = models.DateTimeField(verbose_name='创建时间')  # 创建时间
    cover_photo = models.FileField(upload_to="cover_photo/", default="cover_photo/default.png", verbose_name="封面图片")
    is_draft = models.IntegerField(verbose_name='是否为草稿', default=1)
    is_review = models.IntegerField(verbose_name='是否审核', default=0)
    is_release = models.IntegerField(verbose_name='是否发布', default=0)
    is_recycle = models.IntegerField(verbose_name="是否在回收站", default=0)
    browse_count = models.IntegerField(verbose_name='浏览数', default=0)
    comment_count = models.IntegerField(verbose_name='评论数', default=0)
    like_count = models.IntegerField(verbose_name='喜欢数', default=0)
    user = models.ForeignKey(to="UserInfo", to_field="nid", on_delete=models.CASCADE)
    classification = models.ForeignKey(to="Classification", to_field="nid", on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0, editable=False, verbose_name="阅读数")
    # 采用 Django-taggit 库
    tags = TaggableManager(blank=False, through=None)

    def __str__(self):
        return self.title

    # 浏览数，每一次浏览都自动加一
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_tags(self):
        tags = []
        self.tags.all()
        tags.append(str(tags))
        return ','.join(tags)

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('front_end:article_detail', args=[self.nid])


class ArticleDetail(models.Model):
    """
    文章详情表

    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article = models.OneToOneField(to="Article", to_field="nid", on_delete=models.CASCADE)


class ArticleLike(models.Model):
    """
    喜欢表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo", to_field="nid", null=True, on_delete=models.CASCADE)
    article = models.ForeignKey(to="Article", to_field="nid", null=True, on_delete=models.CASCADE)
    like_ip = models.CharField(max_length=20, verbose_name="评论电脑的IP", null=True)

    class Meta:
        unique_together = (("article", "user"),)


class Comment(MPTTModel):
    """
    评论表
    """
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE, related_name='comments')
    # mptt树形结构
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    # 记录二级评论回复给谁, str
    reply_to = models.ForeignKey(UserInfo, null=True, blank=True, on_delete=models.CASCADE, related_name='replyers')
    body = models.CharField(max_length=800)  # 评论内容
    created = models.DateTimeField(verbose_name='创建时间')

    class MPTTMeta:
        order_insertion_by = ["-created"]

    def __str__(self):
        return self.body



class ad_poster(models.Model):
    """
    广告
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=20, verbose_name="广告标题")
    ad_url = models.CharField(max_length=50, verbose_name="广告链接")
    ad_photo = models.FileField(upload_to="advertisement/", verbose_name="广告图片")
    is_show = models.IntegerField(default=1, verbose_name="是否在前台展示")
    is_rotation = models.IntegerField(default=1, verbose_name="是否在前台轮播展示")
    create_time = models.DateTimeField(verbose_name='创建时间')  # 创建时间


class Links(models.Model):
    """
    :友情链接
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=30, verbose_name="链接名")
    url = models.CharField(max_length=50, verbose_name="链接URL")
    create_time = models.DateTimeField(verbose_name='创建时间')  # 创建时间
    is_show = models.IntegerField(default=1, verbose_name="是否在前台展示")

front_end/forms.py
"""
blog用到的form类
"""

from django import forms
from django.core.exceptions import ValidationError
from front_end import models
from mptt.models import MPTTModel


class RegForm(forms.Form):
    username = forms.CharField(
        max_length=16,
        label='用户名',
        error_messages={
            "required": "用户名不能为空！",
            "max_length": "用户名最长不能超过16位",
        },
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control",
            },
        )
    )
    password = forms.CharField(
        min_length=6,
        label='密码',
        error_messages={
            "required": "密码不能为空！",
            "min_length": "密码最短不能少于6位",
        },
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"},
            render_value=True,
        )
    )
    re_password = forms.CharField(
        label='确认密码',
        error_messages={
            "required": "确认密码不能为空！",
        },
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"},
            render_value=True,
        )
    )
    email = forms.EmailField(
        label="常用邮件地址",
        widget=forms.widgets.EmailInput(
            attrs={"class": "form-control"},

        ),
        error_messages={
            "invalid": "邮箱格式不正确！",
            "required": "邮箱不能为空!",
        }
    )

    # 重写username的局部钩子，对用户名是否存在做校验
    def clean_username(self):
        username = self.cleaned_data.get("username")
        is_exist = models.UserInfo.objects.filter(username=username)
        if is_exist:
            self.add_error("username", ValidationError("用户名已存在！"))
        else:
            return username

    # 重写email的局部钩子，对用户名是否存在做校验
    def clean_email(self):
        email = self.cleaned_data.get("email")
        is_exist = models.UserInfo.objects.filter(email=email)
        if is_exist:
            self.add_error("email", ValidationError("邮箱已存在！"))
        else:
            return email

    # 重写全局的钩子函数，对确认密码做校验
    def clean(self):
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")

        if re_password and re_password != password:
            self.add_error("re_password", ValidationError("两次密码不一致！"))
        else:
            return self.cleaned_data


# 写文章的表单类
class ArticleForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = models.Article
        # 定义表单包含的字段
        fields = ('title', 'tags', 'cover_photo')


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['body']

templates/front_end/article_category.html
{% extends 'front_end/master.html' %}

{% block classification %}
    <!-- 文章分类 开始-->
    {% for article in page.object_list %}
        <div class="div-back avatar-div-img">
            <div class="article-div"><p><span><a
                    href="/article_category/{{ article.classification.title }}/">{{ article.classification.title }}
                <i class="fa fa-gg" aria-hidden="true"></i></a></span>
                <a href="/acticle_details/{{ article.pk }}/">{{ article.title }}</a></p>
            </div>
            <div class="media">
                <div class="media-left">
                    <div class="article-img">
                        <a href="/acticle_details/{{ article.pk }}/">
                            <img id="img-article" class="media-object" src="/media/{{ article.cover_photo }}" alt="...">
                        </a>
                    </div>
                </div>
                <div class="media-body">
                    <p class="article-p">{{ article.desc }}</p>
                </div>
            </div>
            <div class="article-footer">
                        <span class="name"><i class="fa fa-user "></i>&nbsp;<a
                                href="/author/{{ article.user.pk }}/">{{ article.user.username }}</a></span>
                <span><i class="fa fa-clock-o"
                         aria-hidden="true"></i>&nbsp;{{ article.create_time|date:'Y-m-d H:i' }}</span>
                <span><i class="fa fa-commenting-o fa-fw"
                         aria-hidden="true"></i>评论({{ article.comment_count }})</span>
                 <span><a onclick="likes_count({{ article.pk }})" href="#"
                                                style="color: #F78585;font-weight: normal;"><i class="fa fa-heart-o" aria-hidden="true"></i>喜欢({{ article.like_count }})</a>
                </span>
            </div>
            <div style="width:100%; height:10px;clear:both;"></div>
        </div>
        <div style="width:100%; height:10px;background: #eee"></div>
    {% endfor %}
    {% include "front_end/home_page.html" %}
    <!--文章分类结束-->
{% endblock %}

{% block jquery %}
    <script src="/static/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="http://pv.sohu.com/cityjson/getip.aspx" charset="utf-8"></script>
    <script type="text/javascript">
        function likes_count(id) {
            var ip = returnCitySN.cip;
            $.ajax({
                url: "/article_like/",
                type: "post",
                data: {
                    "article_id": id,
                    "ip": ip,
                },
                success: function (data) {
                    if (data['status'] === 1) {
                        alert(data['msg']);
                        window.location.reload(); //刷新当前页
                    } else {
                        alert(data['msg']);
                    }
                },
            })
        }
    </script>
{% endblock %}

templates/front_end/article_class.html
{% for class in title_all %}
    <li>
        <a href="/article_category/{{ class.title }}/">{{ class.title }}</a>
    </li>
{% endfor %}

templates/front_end/article_data.html
{% extends 'front_end/master.html' %}

{% block classification %}
    <!-- 文章分类 开始-->
    {% for article in page.object_list %}
        <div class="div-back avatar-div-img">
            <div class="article-div"><p><span><a
                    href="/article_category/{{ article.classification.title }}/">{{ article.classification.title }}
                <i class="fa fa-gg" aria-hidden="true"></i></a></span>
                <a href="/acticle_details/{{ article.pk }}/">{{ article.title }}</a></p>
            </div>
            <div class="media">
                <div class="media-left">
                    <div class="article-img">
                        <a href="/acticle_details/{{ article.pk }}/">
                            <img id="img-article" class="media-object" src="/media/{{ article.cover_photo }}" alt="...">
                        </a>
                    </div>
                </div>
                <div class="media-body">
                    <p class="article-p">{{ article.desc }}</p>
                </div>
            </div>
            <div class="article-footer">
                        <span class="name"><i class="fa fa-user "></i>&nbsp;<a
                                href="/author/{{ article.user.pk }}/">{{ article.user.username }}</a></span>
                <span><i class="fa fa-clock-o"
                         aria-hidden="true"></i>&nbsp;{{ article.create_time|date:'Y-m-d H:i' }}</span>
                <span><i class="fa fa-commenting-o fa-fw"
                         aria-hidden="true"></i>评论({{ article.comment_count }})</span>
                <span><a onclick="likes_count({{ article.pk }})" href="#"
                                                style="color: #F78585;font-weight: normal;"><i class="fa fa-heart-o" aria-hidden="true"></i>喜欢({{ article.like_count }})</a>
                </span>
            </div>
            <div style="width:100%; height:10px;clear:both;"></div>
        </div>
        <div style="width:100%; height:10px;clear:both;background: #eee;"></div>
    {% endfor %}
    {% include "front_end/home_page.html" %}
    <!--文章分类结束-->
{% endblock %}
{% block jquery %}
    <script src="/static/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="http://pv.sohu.com/cityjson/getip.aspx" charset="utf-8"></script>
    <script type="text/javascript">
        function likes_count(id) {
            var ip = returnCitySN.cip;
            $.ajax({
                url: "/article_like/",
                type: "post",
                data: {
                    "article_id": id,
                    "ip": ip,
                },
                success: function (data) {
                    if (data['status'] === 1) {
                        alert(data['msg']);
                        window.location.reload(); //刷新当前页
                    } else {
                        alert(data['msg']);
                    }
                },
            })
        }
    </script>
{% endblock %}

templates/front_end/author_article.html
{% extends "front_end/master.html" %}

{% block other %}
    {% for article in page.object_list %}
        <div class="div-back avatar-div-img">
            <div class="article-div"><p><span><a
                    href="/article_category/{{ article.classification.title }}/">{{ article.classification.title }}
                <i class="fa fa-gg" aria-hidden="true"></i></a></span>
                <a href="/acticle_details/{{ article.pk }}/">{{ article.title }}</a></p>
            </div>
            <div class="media">
                <div class="media-left">
                    <div class="article-img">
                        <a href="/acticle_details/{{ article.pk }}/">
                            <img id="img-article" class="media-object" src="/media/{{ article.cover_photo }}" alt="...">
                        </a>
                    </div>
                </div>
                <div class="media-body">
                    <p class="article-p">{{ article.desc }}</p>
                </div>
            </div>
            <div class="article-footer">
                <span><i class="fa fa-clock-o"
                         aria-hidden="true"></i>&nbsp;{{ article.create_time|date:'Y-m-d H:i' }}</span>
                <span><i class="fa fa-commenting-o fa-fw"
                         aria-hidden="true"></i>评论({{ article.comment_count }})</span>
                <span><a onclick="likes_count({{ article.pk }})" href="#"
                                                style="color: #F78585;font-weight: normal;"><i class="fa fa-heart-o" aria-hidden="true"></i>喜欢({{ article.like_count }})</a></span>
            </div>
            <div style="width:100%; height:10px;clear:both;"></div>
        </div>
        <div style="width:100%; height:10px;clear:both;"></div>
    {% endfor %}
    {% include "front_end/home_page.html" %}
{% endblock %}
{% block jquery %}
<script type="text/javascript" src="http://pv.sohu.com/cityjson/getip.aspx" charset="utf-8"></script>
    <script type="text/javascript">
        function likes_count(id) {
            var ip = returnCitySN.cip;
            $.ajax({
                url: "/article_like/",
                type: "post",
                data: {
                    "article_id": id,
                    "ip": ip,
                },
                success: function (data) {
                    if (data['status'] === 1) {
                        alert(data['msg']);
                        window.location.reload(); //刷新当前页
                    } else {
                        alert(data['msg']);
                    }
                },
            })
        }
    </script>
{% endblock %}

templates/front_end/forgot_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>忘记密码表单</title>
    {% load static %}
    <link rel="SHORTCUT ICON" href="{% static "/img/favicon.ico" %}"/>
    <link rel="stylesheet" href="{% static '/my_style.css' %}">
</head>
<body background="/static/img/login_bj.jpg">
<div id="forgot_password_head">
    <p>请输入您的用户名或电子邮箱地址。您会收到一封包含创建新密码链接的电子邮件。</p>
</div>
<div id="forgot_password_errors">
    <p id="forgot_password_error"></p>
</div>
<div id="forgot_password_index">
    <div id="login_form">
        <table id="forgot_password_table">
            <tbody>
            <tr>
                <td><p>用户名或电子邮件地址</p><input type="text" id="forgot_username"></td>
            </tr>
            <tr>
                <td>
                    <button id="forgot_submit">获取新密码</button>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<div id="login_other">
    <p><span><a href="/login/">登录</a></span>&nbsp;|&nbsp;<span><a href="/register/">注册</a></span></p>
    <p><a href="/home/">返回主页</a></p>
</div>
<script src="{% static '/jquery-3.3.1.js' %}"></script>
<script>
    {# 将整个html里的input标签加上 autocomplete='off'#}
    $(function () {
        $('input:not([autocomplete])').attr('autocomplete', 'off');
    });
</script>
<script>
    // AJAX提交注册的数据
    $("#forgot_submit").click(function () {
        // 取到用户填写的注册数据，向后端发送AJAX请求
        var username = $("#forgot_username").val()
        $.ajax({
            url: "/forgot_password/",
            type: "post",
            data: {
                username: username,
                csrfmiddlewaretoken: '{{ csrf_token }}',
            },
            success: function (data) {
                if (data.status === 1) {
                    // 有错误就展示错误
                    // 将报错信息填写到页面上
                    $("#forgot_password_error").text(data.msg).addClass("errors");

                } else {
                    // 没有错误就跳转到指定页面
                    alert("请前往邮箱进行修改！");
                    location.href = data.msg;
                }

            }
        })
    });

    // 当input框绑定获取焦点的事件，就将错误信息清空
    $("#forgot_username").focus(function () {
        $("#forgot_password_error").text("").removeClass("errors");
    });

</script>
</body>
</html>

templates/front_end/home_page.html
{% if page.paginator.num_pages > 1 %}
<div class="home_page" style="width: 100%;">
    <ul>
        <li><a href="?page=1">首页</a></li>
        {% if page.has_previous %}
            <li><a href="?{{ page.previous_page_number.querystring }}">&lsaquo;&lsaquo; </a></li>
        {% else %}
            <li><span class="span_disabled">&lsaquo;&lsaquo; </span></li>
        {% endif %}
        {% for page in page.pages %}
        {% if page %}
        {% ifequal page page.number %}
        <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
        {% else %}
        <li id="li_active"><a id="a{{ page }}" href="?{{ page.querystring }}">{{ page }}</a></li>
        {% endifequal %}
        {% else %}
        ...
        {% endif %}
        {% endfor %}
        {% if page.has_next %}
            <li><a href="?{{ page.next_page_number.querystring }}"> &rsaquo;&rsaquo;</a>
            </li>
        {% else %}
            <li><span class="span_disabled"> &rsaquo;&rsaquo;</span></li>
        {% endif %}
        <li><a href="?page={{ page.paginator.num_pages }}">尾页</a></li>

    </ul>
</div>
{% else %}
{% endif %}

templates/front_end/links.html
<div class="div-back" style="margin-top: 10px;">
    <div style="text-align: left;padding-top: 10px;font-size: 18px;color:#737373;padding-left: 20px;">友情链接</div>
    <div style="margin-top: 10px; border-top: solid #00a67c 1px;"></div>
    <div style="padding: 0 10px 10px 10px;width: 100%;">
        <ul class="my_ul" style=" list-style-type:none;text-align:left; padding: 0 10px 20px 10px;">
            {% for link in links %}
                <li style="float:left;width:50%;padding-bottom:5px;">
                    <p class="home_p" style="color: #00a67c"><a href="{{ link.url }}">{{ link.title }}</a></p></li>
            {% endfor %}
        </ul>
    <div style="clear:both;"></div>
    </div>
</div>

templates/front_end/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册表单</title>
    {% load static %}
    <link rel="SHORTCUT ICON" href="{% static "/img/favicon.ico" %}"/>
    <link rel="stylesheet" href="{% static '/my_style.css' %}">
</head>
<body background="/static/img/login_bj.jpg">
<div id="register_head">
    <p>在这个站点注册</p>
</div>
<div id="errors">
    <div id="username_errors">
        <p id="error_username">{{ form_obj.username.errors.0 }}</p>
    </div>
    <div id="email_errors">
        <p id="error_email">{{ form_obj.email.errors.0 }}</p>
    </div>
    <div id="password_errors">
        <p id="error_password">{{ form_obj.password.errors.0 }}</p>
    </div>
    <div id="re_password_errors">
        <p id="error_re_password">{{ form_obj.re_password.errors.0 }}</p>
    </div>
</div>
<div id="register_index">
    <div id="register_form">
        <table id="register_table">
            <tbody>
            <tr>
                <td><p><label for="{{ form_obj.username.id_for_label }}">{{ form_obj.username.label }}</label></p>
                    {{ form_obj.username }}</td>
            </tr>
            <tr>
                <td><p><label for="{{ form_obj.email.id_for_label }}">{{ form_obj.email.label }}</label></p>

                    {{ form_obj.email }} <span class="help-block">{{ form_obj.email.errors.0 }}</span>
                </td>
            </tr>
            <tr>
                <td><p><label for="{{ form_obj.password.id_for_label }}">{{ form_obj.password.label }}</label></p>
                    {{ form_obj.password }}</td>
            </tr>
            <tr>
                <td><p><label for="{{ form_obj.re_password.id_for_label }}">{{ form_obj.re_password.label }}</label></p>
                    {{ form_obj.re_password }}</td>
            </tr>
            <tr>
                <td><p>注册确认信将会发送到您的邮箱.</p></td>
            </tr>
            <tr>
                <td>
                    <button id="reg-submit">注 册</button>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<div id="login_other">
    <p><span><a href="/login/">登录</a></span>&nbsp;|&nbsp;<span><a href="/forgot_password/">忘记密码?</a></span></p>
    <p><a href="/home/">返回主页</a></p>
</div>
<script src="{% static '/jquery-3.3.1.js' %}"></script>
<script>
    {# 将整个html里的input标签加上 autocomplete='off'#}
    $(function () {
        $('input:not([autocomplete])').attr('autocomplete', 'off');

    });
</script>
<script>
    // AJAX提交注册的数据
    $("#reg-submit").click(function () {
        // 取到用户填写的注册数据，向后端发送AJAX请求
        var formData = new FormData();
        formData.append("username", $("#id_username").val());
        formData.append("password", $("#id_password").val());
        formData.append("re_password", $("#id_re_password").val());
        formData.append("email", $("#id_email").val());
        formData.append("csrfmiddlewaretoken", '{{ csrf_token }}');
        $.ajax({
            url: "/register/",
            type: "post",
            processData: false,
            contentType: false,
            data: formData,
            success: function (data) {
                if (data.status === 1) {
                    // 有错误就展示错误
                    // 将报错信息填写到页面上
                    $.each(data.msg, function (k, v) {
                        // console.log("id_"+k, v[0]);
                        // console.log($("#id_"+k));
                        $("#error_" + k).text(v[0]).addClass("has-error errors");
                    })

                } else if (data.status === 2) {
                    alert(data.msg);
                } else {
                    // 没有错误就跳转到指定页面
                    alert("请前往邮箱进行确认！");
                    location.href = data.msg;
                }

            }
        })
    });

    // 当input框绑定获取焦点的事件，就将错误信息清空
    $("#id_email").focus(function () {
        $("#error_email").text("").removeClass("has-error errors");
    });
    $("#id_password").focus(function () {
        $("#error_password").text("").removeClass("has-error errors");
    });
    $("#id_re_password").focus(function () {
        $("#error_re_password").text("").removeClass("has-error errors");
    });

    // 给username input框绑定一个失去焦点的事件，失去焦点之后就校验用户名是否已被注册
    $("#id_username").on("input", function () {
        // 取到用户填写的值
        var username = $(this).val();
        if (username == null || username === "") {
            $("#error_username").text("").removeClass("has-error");
        } else {
            // 发请求
            $.ajax({
                url: "/check_username_exist/",
                type: "get",
                data: {"username": username},
                success: function (data) {
                    if (data.status) {
                        // 用户名已被注册
                        $("#error_username").text(data.msg).addClass("has-error errors");
                    } else {
                        $("#error_username").text("").removeClass("has-error errors");
                    }
                }
            })
        }

    })
</script>
{#<script>#}
{#    window.onload = function () {#}
{#        var errors = document.getElementById("errors").getElementsByTagName("p")#}
{#        for (var i = 0; i < errors.length; i++) {#}
{#            if (errors[i].className === "has-error") {#}
{#                $(".has-error").addClass("errors")#}
{#            }#}
{#        }#}
{#    }#}
{#</script>#}
</body>
</html>